version: "3"
services:
  frontend:
    image: nginx:latest
    container_name: frontend-travel
    ports:
      - "8080:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro

  backend:
    build: backend
    depends_on:
      database:
        condition: service_healthy
    environment:
      - PGURI=${PGURI}
    ports:
      - '3000:3000'
  database:
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
    healthcheck:
      interval: 2s
      retries: 5
      test: 'pg_isready --username=${DB_USER}'
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
